ALTER TABLE "public"."application_answers" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."application_scores" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."application_stage_history" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."applications" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."audit_events" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."background_checks" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."branches" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."candidate_consents" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."candidate_documents" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."candidate_employee_links" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."candidate_notes" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."candidate_tags" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."candidates" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."departments" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."employee_certifications" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."employee_disciplinary_records" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."employee_documents" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."employee_exit_processes" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."employee_qualifications" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."employee_skills" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."employee_user_links" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."employees" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."employment_periods" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."interview_panel_members" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."interview_scorecard_responses" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."interview_scorecards" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."interviews" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."job_requisitions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."leave_balance_entries" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."leave_policies" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."leave_requests" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."leave_types" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."master_data_domains" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."master_data_items" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."membership_roles" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."membership_scopes" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."modules" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."notifications" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."offer_approvals" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."offer_versions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."offers" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."organization_domains" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."organization_memberships" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."organization_modules" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."organization_relationships" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."organization_settings" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."organization_types" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."organizations" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."permissions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."positions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."pre_employment_requirements" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."primary_hr_assignments" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."public_holidays" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."recruitment_settings" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."recruitment_stages" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."recruitment_workflows" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."reference_checks" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."reports" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."requisition_approvals" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."role_permissions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."roles" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."sessions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."talent_pool_members" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."talent_pools" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."users" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."vacancies" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."vacancy_locations" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "public"."vacancy_questions" ENABLE ROW LEVEL SECURITY;
