import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import organizationsRouter from "./organizations";
import notificationsRouter from "./notifications";
import usersRouter from "./users";
import meRouter from "./me";
import employeesRouter from "./employees";
import employeeSkillsQualificationsRouter from "./employeeSkillsQualifications";
import employeeDisciplinaryRecordsRouter from "./employeeDisciplinaryRecords";
import employeeExitProcessRouter from "./employeeExitProcess";
import leaveTypesRouter from "./leaveTypes";
import leaveRequestsRouter from "./leaveRequests";
import leaveBalancesRouter from "./leaveBalances";
import leaveApprovalsRouter from "./leaveApprovals";
import leaveCalendarRouter from "./leaveCalendar";
import publicHolidaysRouter from "./publicHolidays";
import recruitmentSettingsRouter from "./recruitmentSettings";
import recruitmentWorkflowsRouter from "./recruitmentWorkflows";
import jobRequisitionsRouter from "./jobRequisitions";
import vacanciesRouter from "./vacancies";
import publicCareersRouter from "./publicCareers";
import applicationsRouter from "./applications";
import candidatesRouter from "./candidates";
import talentPoolsRouter from "./talentPools";
import interviewsRouter from "./interviews";
import interviewScorecardsRouter from "./interviewScorecards";
import referenceChecksRouter from "./referenceChecks";
import backgroundChecksRouter from "./backgroundChecks";
import offersRouter from "./offers";
import preEmploymentRequirementsRouter from "./preEmploymentRequirements";
import employeeConversionRouter from "./employeeConversion";
import branchesRouter from "./branches";
import departmentsRouter from "./departments";
import positionsRouter from "./positions";
import rolesRouter from "./roles";
import permissionsRouter from "./permissions";
import membersRouter from "./members";
import primaryHrRouter from "./primaryHr";
import organizationSettingsRouter from "./organizationSettings";
import auditEventsRouter from "./auditEvents";
import modulesRouter from "./modules";
import organizationModulesRouter from "./organizationModules";
import masterDataRouter from "./masterData";
import invitationsRouter from "./invitations";
import organizationRolesRouter from "./organizationRoles";
import reportsRouter from "./reports";
import recruitmentReportingRouter from "./recruitmentReporting";
import organizationDomainsRouter from "./organizationDomains";
import tenantContextRouter from "./tenantContext";
import attendanceEventsRouter from "./attendanceEvents";
import attendanceAdjustmentsRouter from "./attendanceAdjustments";
import attendanceDailySummaryRouter from "./attendanceDailySummary";
import attendanceRegisterRouter from "./attendanceRegister";
import attendanceReportingRouter from "./attendanceReporting";
import performanceRatingScalesRouter from "./performanceRatingScales";
import performanceReviewTemplatesRouter from "./performanceReviewTemplates";
import performanceCyclesRouter from "./performanceCycles";
import performanceReviewGoalsRouter from "./performanceReviewGoals";
import performanceSelfAssessmentRouter from "./performanceSelfAssessment";
import performanceManagerReviewRouter from "./performanceManagerReview";
import performanceHrReviewRouter from "./performanceHrReview";
import performanceReportingRouter from "./performanceReporting";
import performanceReviewEvidenceRouter from "./performanceReviewEvidence";
import performanceAcknowledgementRouter from "./performanceAcknowledgement";
import learningCoursesRouter from "./learningCourses";
import learningCourseSessionsRouter from "./learningCourseSessions";
import learningEnrollmentsRouter from "./learningEnrollments";
import learningCertificatesRouter from "./learningCertificates";
import learningEnrollmentEvidenceRouter from "./learningEnrollmentEvidence";
import learningReportingRouter from "./learningReporting";
import assetsRouter from "./assets";
import assetReportingRouter from "./assetReporting";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(organizationsRouter);
router.use(notificationsRouter);
router.use(usersRouter);
router.use(meRouter);
router.use(employeesRouter);
router.use(employeeSkillsQualificationsRouter);
router.use(employeeDisciplinaryRecordsRouter);
router.use(employeeExitProcessRouter);
router.use(leaveTypesRouter);
router.use(leaveRequestsRouter);
router.use(leaveBalancesRouter);
router.use(leaveApprovalsRouter);
router.use(leaveCalendarRouter);
router.use(publicHolidaysRouter);
router.use(recruitmentSettingsRouter);
router.use(recruitmentWorkflowsRouter);
router.use(jobRequisitionsRouter);
router.use(vacanciesRouter);
router.use(publicCareersRouter);
router.use(applicationsRouter);
router.use(candidatesRouter);
router.use(talentPoolsRouter);
router.use(interviewsRouter);
router.use(interviewScorecardsRouter);
router.use(referenceChecksRouter);
router.use(backgroundChecksRouter);
router.use(offersRouter);
router.use(preEmploymentRequirementsRouter);
router.use(employeeConversionRouter);
router.use(branchesRouter);
router.use(departmentsRouter);
router.use(positionsRouter);
router.use(rolesRouter);
router.use(permissionsRouter);
router.use(membersRouter);
router.use(primaryHrRouter);
router.use(organizationSettingsRouter);
router.use(auditEventsRouter);
router.use(modulesRouter);
router.use(organizationModulesRouter);
router.use(masterDataRouter);
router.use(invitationsRouter);
router.use(organizationRolesRouter);
router.use(reportsRouter);
router.use(recruitmentReportingRouter);
router.use(organizationDomainsRouter);
router.use(tenantContextRouter);
router.use(attendanceEventsRouter);
router.use(attendanceAdjustmentsRouter);
router.use(attendanceDailySummaryRouter);
router.use(attendanceRegisterRouter);
router.use(attendanceReportingRouter);
router.use(performanceRatingScalesRouter);
router.use(performanceReviewTemplatesRouter);
router.use(performanceCyclesRouter);
router.use(performanceReviewGoalsRouter);
router.use(performanceSelfAssessmentRouter);
router.use(performanceManagerReviewRouter);
router.use(performanceHrReviewRouter);
router.use(performanceReportingRouter);
router.use(performanceReviewEvidenceRouter);
router.use(performanceAcknowledgementRouter);
router.use(learningCoursesRouter);
router.use(learningCourseSessionsRouter);
router.use(learningEnrollmentsRouter);
router.use(learningCertificatesRouter);
router.use(learningEnrollmentEvidenceRouter);
router.use(learningReportingRouter);
// assetReportingRouter MUST be registered before assetsRouter: Express
// matches routes in registration order, and assetsRouter's own
// GET .../assets/:id would otherwise swallow GET .../assets/dashboard
// (treating "dashboard" as an invalid numeric id) — the identical ordering
// bug W98 already found and fixed for my-assets/team-assets.
router.use(assetReportingRouter);
router.use(assetsRouter);

export default router;
