import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import organizationsRouter from "./organizations";
import notificationsRouter from "./notifications";
import usersRouter from "./users";
import meRouter from "./me";
import employeesRouter from "./employees";
import branchesRouter from "./branches";
import departmentsRouter from "./departments";
import positionsRouter from "./positions";
import rolesRouter from "./roles";
import permissionsRouter from "./permissions";
import membersRouter from "./members";
import primaryHrRouter from "./primaryHr";
import organizationSettingsRouter from "./organizationSettings";
import auditEventsRouter from "./auditEvents";
import modulesRouter from "./modules";
import organizationModulesRouter from "./organizationModules";
import masterDataRouter from "./masterData";
import invitationsRouter from "./invitations";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(organizationsRouter);
router.use(notificationsRouter);
router.use(usersRouter);
router.use(meRouter);
router.use(employeesRouter);
router.use(branchesRouter);
router.use(departmentsRouter);
router.use(positionsRouter);
router.use(rolesRouter);
router.use(permissionsRouter);
router.use(membersRouter);
router.use(primaryHrRouter);
router.use(organizationSettingsRouter);
router.use(auditEventsRouter);
router.use(modulesRouter);
router.use(organizationModulesRouter);
router.use(masterDataRouter);
router.use(invitationsRouter);

export default router;
