import { pgTable, text, serial, timestamp, integer, pgEnum, uuid, uniqueIndex } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";
import { organizationTypesTable } from "./organization-types";

export const orgTypeEnum = pgEnum("org_type", [
  "business",
  "church",
  "ngo",
  "school",
  "hospital",
  "hotel",
  "government",
  "other",
]);

export const orgStatusEnum = pgEnum("org_status", [
  "active",
  "suspended",
  "trial",
]);

// Tenant identity contract (docs/TENANT_IDENTITY_AND_CUSTOMIZATION.md):
//
//   id          — internal primary key. Every tenant-owned table references
//                 it; it is the security boundary and never changes.
//   tenant_uuid — the immutable, globally unique tenant identity. Unlike the
//                 serial `id`, it survives a tenant moving between
//                 installations (a hosted -> dedicated move remaps serial
//                 keys), so it is the identifier to quote in support,
//                 maintenance and change requests. Generated by the database,
//                 never client-supplied, never updated (a BEFORE UPDATE trigger
//                 in migration 0075 rejects any change to id or tenant_uuid).
//   slug        — the human-readable tenant code. Unique, validated at
//                 creation, immutable through the API after creation.
//   name        — display name only. Never a security boundary; renaming an
//                 organization changes nothing about who owns its data.
export const organizationsTable = pgTable(
  "organizations",
  {
    id: serial("id").primaryKey(),
    tenantUuid: uuid("tenant_uuid").notNull().defaultRandom(),
    name: text("name").notNull(),
    slug: text("slug").notNull().unique(),
    type: orgTypeEnum("type").notNull().default("business"),
    // Additive, nullable, not yet authoritative — `type` above remains the
    // source of truth until a later phase migrates callers over.
    organizationTypeId: integer("organization_type_id").references(() => organizationTypesTable.id, {
      onDelete: "restrict",
    }),
    status: orgStatusEnum("status").notNull().default("trial"),
    logoUrl: text("logo_url"),
    industry: text("industry"),
    employeeCount: integer("employee_count"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
  },
  (table) => [uniqueIndex("organizations_tenant_uuid_unique").on(table.tenantUuid)],
);

export const insertOrganizationSchema = createInsertSchema(organizationsTable).omit({
  id: true,
  tenantUuid: true,
  createdAt: true,
  updatedAt: true,
});

export type InsertOrganization = z.infer<typeof insertOrganizationSchema>;
export type Organization = typeof organizationsTable.$inferSelect;
